server:
  port : 8080
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: "./road-trip-api/keystore.p12"
    key-store-type: PKCS12
    key-store-password: password
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
