version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 'road-trip-planner'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uadmin", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20
